# Generated by Django 6.0.8 on 2026-08-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='email_contact',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='commande',
            name='info_complementaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('WAVE', 'Wave'), ('ORANGE_MONEY', 'Orange Money'), ('ESPECES', 'Espèces à la livraison')], max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='prenom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
