# Generated by Django 6.0.8 on 2026-08-20 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_adresse_livraison_commande_email_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=8)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='commande',
            name='reference_paiement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='commande',
            name='zone_livraison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='commandes.zonelivraison'),
        ),
    ]
