# Generated by Django 6.0.8 on 2026-08-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_avis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-id']},
        ),
    ]
