import dj_database_url
from decouple import Csv, config
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())

CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'catalogue',
    'panier',
    'commandes',
    'comptes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'catalogue.context_processors.categories_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# En local, on construit l'URL a partir des DB_* de .env. En production,
# la plateforme d'hebergement fournit directement DATABASE_URL (Neon,
# Render...), qui prend le dessus automatiquement.
_url_db_locale = (
    f"postgresql://{config('DB_USER', default='')}:{config('DB_PASSWORD', default='')}"
    f"@{config('DB_HOST', default='')}:{config('DB_PORT', default='')}/{config('DB_NAME', default='')}"
)

DATABASES = {
    'default': dj_database_url.config(default=_url_db_locale, conn_max_age=600)
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = 'comptes:login'
LOGIN_REDIRECT_URL = 'catalogue:liste_produits'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
# Sans delai, une connexion SMTP qui reste bloquee (frequent sur certains
# hebergeurs) fait planter le worker Gunicorn entier au bout de 30s au lieu
# d'echouer proprement. On coupe court bien avant.
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')

# Envoi des emails transactionnels (code de confirmation d'inscription) via
# l'API HTTP de Brevo plutot que le SMTP Gmail : Gmail bloque/ralentit trop
# souvent les connexions depuis les IP d'hebergeurs cloud comme Render, ce
# qui provoquait des inscriptions bloquees. L'API HTTP (port 443, comme le
# reste du site) evite ce probleme.
BREVO_API_KEY = config('BREVO_API_KEY', default='')

SITE_URL = config('SITE_URL', default='http://127.0.0.1:8000')

# Paiement Wave : cle secrete depuis le tableau de bord Wave Business
WAVE_API_KEY = config('WAVE_API_KEY', default='')

# Paiement Orange Money : identifiants depuis le portail Orange Developer
ORANGE_MONEY_CLIENT_ID = config('ORANGE_MONEY_CLIENT_ID', default='')
ORANGE_MONEY_CLIENT_SECRET = config('ORANGE_MONEY_CLIENT_SECRET', default='')
ORANGE_MONEY_MERCHANT_KEY = config('ORANGE_MONEY_MERCHANT_KEY', default='')

# Secrets pour verifier que les webhooks de paiement viennent bien de Wave/Orange
WAVE_WEBHOOK_SECRET = config('WAVE_WEBHOOK_SECRET', default='')
ORANGE_MONEY_WEBHOOK_SECRET = config('ORANGE_MONEY_WEBHOOK_SECRET', default='')

# SMS de confirmation de commande : identifiants depuis la console Twilio
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_FROM_NUMBER = config('TWILIO_FROM_NUMBER', default='')


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Reglage historique garde en parallele : django-cloudinary-storage ne
# connait pas encore le nouveau dictionnaire STORAGES de Django.
STATICFILES_STORAGE = STORAGES['staticfiles']['BACKEND']

# Evite un echec de collectstatic si un fichier statique tiers (ex. admin
# Django) reference une ressource que Whitenoise ne retrouve pas dans son
# manifeste — comportement documente de Whitenoise pour ce cas precis.
WHITENOISE_MANIFEST_STRICT = False

# Stockage des images produits sur Cloudinary (persistant, gratuit) des que
# les identifiants sont configures. Sans ca, les fichiers restent en local
# (media/), ce qui suffit en developpement mais serait perdu a chaque
# redeploiement sur un hebergeur au disque ephemere.
CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='')
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default='')
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default='')

if CLOUDINARY_CLOUD_NAME:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }
    STORAGES['default'] = {'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage'}
